# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87839960f25711789930110e9277ccf7996a6681cfcd3f58c7ab160f85e2fbace37f9941db299a79931ac209f58fc581b0817283cf80feaf9de46a8a6c1970bb

test:
  secret_key_base: 258f4f77351527176ad7abe8e6db4fdd80a13549a71649f07bf85faaa219bbf94e7057d5997607609ca91af569b8cc2620f4de05917dd420ef78ec24442452ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
